<#
.SYNOPSIS
	Convert .resx resource files into idempotent SQL INSERT statements for LocalizationResources.

.DESCRIPTION
	Scans a directory tree for .resx files and emits INSERT ... WHERE NOT EXISTS statements.
	Supports SQLite and SQL Server output formats.

.PARAMETER InputDir
	Directory to scan for .resx files. Defaults to current directory.

.PARAMETER OutputFile
	File to write SQL to. Defaults to ./resx-inserts.sql

.PARAMETER DefaultCulture
	Culture to use for neutral .resx files (e.g., Resources.resx). Defaults to 'en'.

.PARAMETER Provider
	'sqlite' (default) or 'sqlserver' to control SQL dialect.

EXAMPLE
	.\resx-to-sql.ps1 -InputDir .\Resources -OutputFile seed.sql -DefaultCulture en -Provider sqlite

#>

	[string]$InputDir = ".",
	[string]$OutputFile = "resx-inserts.sql",
	[string]$DefaultCulture = "en",
	[ValidateSet('sqlite','sqlserver')][string]$Provider = 'sqlite'
)]

function Escape-Sql([string]$s, [string]$provider) {
	if ($null -eq $s) { return "" }
	# normalize line endings
	$s = $s -replace "\r\n", "\n"
	if ($provider -eq 'sqlite') {
		return $s -replace "'", "''"
	} else {
		return $s -replace "'", "''"
	}
}

if (Test-Path $OutputFile) { Remove-Item $OutputFile }

"-- Generated by resx-to-sql.ps1 on $(Get-Date)" | Out-File -FilePath $OutputFile -Encoding utf8
"-- Provider: $Provider" | Out-File -FilePath $OutputFile -Append -Encoding utf8
"" | Out-File -FilePath $OutputFile -Append -Encoding utf8

$resxFiles = Get-ChildItem -Path $InputDir -Filter *.resx -Recurse -File
foreach ($file in $resxFiles) {
	$fileName = $file.Name
	# attempt to parse culture from filename like Resources.pt.resx or SharedResources.pt-BR.resx
	$culture = $null
	if ($fileName -match '\.([a-z]{2}(?:-[A-Z]{2})?)\.resx$') {
		$culture = $matches[1]
	}
	if ([string]::IsNullOrEmpty($culture)) { $culture = $DefaultCulture }

	try {
		[xml]$xml = Get-Content -Path $file.FullName -Raw
	}
	catch {
		Write-Warning "Failed to load $($file.FullName): $_"
		continue
	}

	$dataNodes = @()
	if ($xml.root -and $xml.root.data) { $dataNodes = $xml.root.data }

	foreach ($d in $dataNodes) {
		$key = $d.name
		$val = $null
		if ($d.value) { $val = $d.value.'#text' }
		if ($null -eq $val) { $val = $d.value }
		$keyEsc = Escape-Sql $key $Provider
		$valEsc = Escape-Sql $val $Provider

		if ($Provider -eq 'sqlite') {
			$insert = "INSERT INTO LocalizationResources (ResourceKey, Culture, ResourceValue, UpdatedAt)"
			$insert += "\nSELECT '$keyEsc', '$culture', '$valEsc', datetime('now')"
			$insert += "\nWHERE NOT EXISTS (SELECT 1 FROM LocalizationResources WHERE ResourceKey = '$keyEsc' AND Culture = '$culture');"
		}
		else {
			# SQL Server T-SQL compatible
			$insert = "IF NOT EXISTS (SELECT 1 FROM LocalizationResources WHERE ResourceKey = '$keyEsc' AND Culture = '$culture')\nBEGIN\n    INSERT INTO LocalizationResources (ResourceKey, Culture, ResourceValue, UpdatedAt) VALUES (N'$keyEsc', N'$culture', N'$valEsc', GETUTCDATE());\nEND"
		}

		$insert | Out-File -FilePath $OutputFile -Append -Encoding utf8
	}
}

Write-Host "SQL written to $OutputFile" -ForegroundColor Green
